spring.application.name=mohassib

# Server
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api/v1

## Database (env vars override defaults; defaults used for local dev)
##spring.datasource.url=${DB_URL:jdbc:postgresql://161.97.129.76:5432/mohassib_db}
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mohassib_db}
##spring.datasource.username=${DB_USER:mohassib_user}
#spring.datasource.username=postgres
##spring.datasource.password=${DB_PASSWORD:StrongPassword123!}
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://161.97.129.76:5432/mohassib_database
spring.datasource.username=mohassib_admin
spring.datasource.password=V<=,a]9O~e4LL/Tw47f3U?n1y/
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

# Files (where generated PDFs may be archived later)
mohassib.files.directory=${FILES_DIR:./storage}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JWT (override JWT_SECRET in production - default is dev only)
mohassib.jwt.secret=${JWT_SECRET:ZGV2LW9ubHktSk5UU2VjcmV0LU5PVC1mb3ItcHJvZHVjdGlvbi1taW4tMjU2LWJpdHM=}
mohassib.jwt.access-token-ttl-minutes=${JWT_ACCESS_TTL_MIN:60}
mohassib.jwt.refresh-token-ttl-days=${JWT_REFRESH_TTL_DAYS:30}
mohassib.jwt.issuer=mohassib

# CORS (frontend dev server)
mohassib.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Logging
logging.level.org.hibernate.SQL=INFO
logging.level.com.elguennouni.mohassib=DEBUG

# Mail config
spring.mail.host=${MAIL_HOST:smtp.zoho.com}
spring.mail.port=${MAIL_PORT:465}
spring.mail.username=${MAIL_USERNAME:mohassib@zohomail.com}
spring.mail.password=${MAIL_PASSWORD:EiHbaxxQ7t3n}
spring.mail.protocol=${MAIL_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SMTP_SSL:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:false}

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:REDACTED-CLIENT-ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:REDACTED-CLIENT-SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE:email,profile}